{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.clientMaxBodySize | default "5m" | quote}}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    {{- if and .Values.ingress.appHost .Values.frontend.enabled }}
    - host: {{ .Values.ingress.appHost }}
      http:
        paths:
          - backend:
              service:
                port:
                  number: 8080
                name: {{ .Release.Name }}-frontend
            path: /
            pathType: Prefix
    {{- end }}
    {{- if and .Values.ingress.api .Values.api.enabled }}
    - host: {{ .Values.ingress.api }}
      http:
        paths:
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-api
            path: /
            pathType: Prefix
    {{- end }}
{{- end }}